// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTiecCuoi.Data;

#nullable disable

namespace QuanLyTiecCuoi.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20250617040053_Them_SLNgayThanhToanTreToiDa")]
    partial class Them_SLNgayThanhToanTreToiDa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.BAOCAOTHANG", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TongTiecCuoi")
                        .HasColumnType("int");

                    b.HasKey("MaBaoCao");

                    b.ToTable("BaoCaoThangs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CASANH", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaCa");

                    b.ToTable("CaSanhs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHITIETBAOCAO", b =>
                {
                    b.Property<int>("MaChiTietBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChiTietBaoCao"));

                    b.Property<decimal>("DoanhThu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaBaoCao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SoLuongTiecCuoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLe")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaChiTietBaoCao");

                    b.HasIndex("MaBaoCao");

                    b.ToTable("ChiTietBaoCaos");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHITIETDVTIEC", b =>
                {
                    b.Property<int>("MaCTDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaCTDV"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaDatTiec")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaCTDV");

                    b.HasIndex("MaDatTiec");

                    b.HasIndex("MaDichVu");

                    b.ToTable("ChiTietDVTiecs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHITIETMENU", b =>
                {
                    b.Property<int>("MaCTMN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaCTMN"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaDatTiec")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaCTMN");

                    b.HasIndex("MaDatTiec");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietMenus");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHUCNANG", b =>
                {
                    b.Property<int>("MaChucNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChucNang"));

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenManHinhDuocLoad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaChucNang");

                    b.ToTable("ChucNangs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.DATTIEC", b =>
                {
                    b.Property<int>("MaDatTiec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDatTiec"));

                    b.Property<TimeSpan>("Gio")
                        .HasColumnType("time(6)");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<int>("MaSanh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDaiTiec")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SoBanDuTru")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<string>("TenChuRe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenCoDau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TienDatCoc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaDatTiec");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaSanh");

                    b.ToTable("DatTiecs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.DICHVU", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.HOADON", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaDatTiec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<decimal>("TienPhaiThanhToan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TienPhat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTienBan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTienDV")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTienHD")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDatTiec");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.LOAISANH", b =>
                {
                    b.Property<int>("MaLoaiSanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLoaiSanh"));

                    b.Property<decimal>("DonGiaBanToiThieu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TenLoaiSanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaLoaiSanh");

                    b.ToTable("LoaiSanhs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.MONAN", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaMon");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.NGUOIDUNG", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNhom");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.NHOMNGUOIDUNG", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomNguoiDungs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.PHANQUYEN", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int>("MaChucNang")
                        .HasColumnType("int");

                    b.HasKey("MaNhom", "MaChucNang");

                    b.HasIndex("MaChucNang");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.SANH", b =>
                {
                    b.Property<int>("MaSanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSanh"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaLoaiSanh")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBanToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenSanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isDelelte")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaSanh");

                    b.HasIndex("MaLoaiSanh");

                    b.ToTable("Sanhs");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.THAMSO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApDungQDPhatThanhToanTre")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PhanTramDatCoc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SLNgayThanhToanTreToiDa")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLePhatThanhToanTreTheoNgay")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("ThamSos");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHITIETBAOCAO", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.BAOCAOTHANG", "BAOCAOTHANG")
                        .WithMany()
                        .HasForeignKey("MaBaoCao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BAOCAOTHANG");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHITIETDVTIEC", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.DATTIEC", "DatTiec")
                        .WithMany()
                        .HasForeignKey("MaDatTiec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTiecCuoi.Data.Models.DICHVU", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTiec");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.CHITIETMENU", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.DATTIEC", "DatTiec")
                        .WithMany()
                        .HasForeignKey("MaDatTiec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTiecCuoi.Data.Models.MONAN", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTiec");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.DATTIEC", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.CASANH", "CaSanh")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTiecCuoi.Data.Models.SANH", "Sanh")
                        .WithMany()
                        .HasForeignKey("MaSanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaSanh");

                    b.Navigation("Sanh");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.HOADON", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.DATTIEC", "DATTIEC")
                        .WithMany()
                        .HasForeignKey("MaDatTiec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DATTIEC");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.NGUOIDUNG", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.NHOMNGUOIDUNG", "NHOMNGUOIDUNG")
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NHOMNGUOIDUNG");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.PHANQUYEN", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.CHUCNANG", "CHUCNANG")
                        .WithMany()
                        .HasForeignKey("MaChucNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTiecCuoi.Data.Models.NHOMNGUOIDUNG", "NHOMNGUOIDUNG")
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CHUCNANG");

                    b.Navigation("NHOMNGUOIDUNG");
                });

            modelBuilder.Entity("QuanLyTiecCuoi.Data.Models.SANH", b =>
                {
                    b.HasOne("QuanLyTiecCuoi.Data.Models.LOAISANH", "LoaiSanh")
                        .WithMany()
                        .HasForeignKey("MaLoaiSanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanh");
                });
#pragma warning restore 612, 618
        }
    }
}
